# Dataset config
"dataset_dir": "data"

# Dataset column definition
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
ITEM_EMB_FIELD: item_emb
TIME_FIELD: timestamp
load_col: {"inter": ["user_id", "item_id", "timestamp"], "emb": ["iid", "item_emb"], "item": ["item_id", "categories", "average_rating", "rating_number"]}

# Sequence config
MAX_ITEM_LIST_LENGTH: 50

# General config
gpu_id: '0'
state: DEBUG
reproducibility: False # set to False for faster training
show_progress: True
seed: 42

# Training config
loss_type: BPR
epochs: 300
stopping_step: 10
learner: 'adam'
learning_rate: 0.001
train_neg_sample_args:
  distribution: 'uniform'
  sample_num: 1
  alpha: 1.0
  dynamic: false
train_batch_size: 2048
neg_sampling:
    uniform: 1
mask_ratio: 0.2
initializer_range: 0.02

# Evaluation config
eval_batch_size: 4096
eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: [5, 10, 20]
valid_metric: MRR@10
metric_decimal_place: 4

# Model Architecture
n_layers: 2                
n_heads: 2      
hidden_size: 64     
inner_size: 256 

# Dropout and Regularization
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
layer_norm_eps: 1e-12

# Activation Function
hidden_act: "gelu"
